fix bpftrace_fuzz error for call to 'get_kernel…_cflags' (#3007)
* fix bpftrace_fuzz error: no matching function for call to 'get_kernel_cflags'

When compiling bpftace_fuzz we run into the following issue where 1
argument is missing, adding the required argument

src/fuzz_main.cpp:140:21: error: no matching function for call to 'get_kernel_cflags'
      extra_flags = get_kernel_cflags(utsname.machine, ksrc, kobj);
                    ^~~~~~~~~~~~~~~~~
src/utils.h:180:26: note: candidate function not viable: requires 4 arguments, but 3 were provided
std::vector<std::string> get_kernel_cflags(const char *uname_machine,
                         ^
Seems fourth argument was added via 4bcee640636e268de4b938a1007fb29a8836f049

Signed-off-by: Gaurav Kamathe <kamathe.gaurav@gmail.com>

---------

Signed-off-by: Gaurav Kamathe <kamathe.gaurav@gmail.com>